language: node_js
node_js:
- "4"
sudo: false
script: npm run $COMMAND
env:
  matrix:
  - COMMAND=test
branches:
  only:
  - master
script
- npm test --cover
after_script:
  - if [[ `node --version` == *v4.5* ]]; then cat ./build/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
